networkservicemesh/cmd-template

.github/workflows/ci.yaml, .github/workflows/pr-for-updates.yaml, .github/workflows/update-cmd-repositories.yaml
=> Update CI scripts and fix bugs

.github/workflows/update-cmd-repositories.yaml
PR fixes https://github.com/networkservicemesh/cmd-template/runs/980079185
=> Add -m option for merge commits into update-cmd-repositories.yaml

.github/workflows/ci.yaml
=> Allow to merge any PRs from nsmbot

.github/workflows/ci.yaml, .github/workflows/update-cmd-repositories.yaml
=> Do not trust to nsmbot merge any files

.github/workflows/update-cmd-repositories.yaml
Fixes https://github.com/networkservicemesh/cmd-template/runs/990493633
=> Simplify adding files to patch

.github/workflows/docker-push.yaml, Dockerfile, main.go
=> Add stub files to make initial CI green for new repositories

.github/workflows/update-cmd-repositories.yaml
=> Subscribe cmd-registry-memory on cmd-template updates

.github/workflows/ci.yaml
=> Add docker pushing job for cmd apps on merge PRs from bot

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml
=> Update checkout actions to v2

.github/workflows/update-cmd-repositories.yaml
=> Subscribe cmd-nsmgr on cmd-template updates

.github/workflows/ci.yaml, .github/workflows/update-cmd-repositories.yaml, exclude.patch.conf
This patch
1. Simplifies restrict dependencies check
2. Fixes restoring repository specific files
3. Adds update-cmd-repositories.yaml to exclude list by default
=> Simplify restrict dependencies check, fix restoring repository specific files

.github/workflows/update-cmd-repositories.yaml
Signed-off-by: Tigran Manasyan <manasyan_tigran@mail.ru>
=> Added cmd-exclude-prefixes-k8s repository to repositories list

.github/workflows/ci.yaml
=> Simplify ci.yaml for cmd-* repositories.

.github/workflows/update-cmd-repositories.yaml
=> fix: Use correct exclude paths relative to the target project

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .github/workflows/update-cmd-repositories.yaml, Dockerfile, go.mod
=> Update go version to v1.15

.github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/update-cmd-repositories.yaml
1. Add codeql-analysis
2. Fix invalid restrictNSMDeps check
`sed 's;.*\(github.com\/networkservicemesh\/[a-zA-z\/]*\).*;\1;g'` truncates `.../sdk-kernel` to `.../sdk`
3. Add `cmd-forwarder-sriov` to dependent repositories
=> Edit template

.github/workflows/update-cmd-repositories.yaml
Fix for https://github.com/networkservicemesh/cmd-template/runs/1306858153
=> Add default .templateignore file in case of subscribing exist repository

.github/workflows/update-cmd-repositories.yaml
=> fix: Do not try to restore files if .templateignore file is empty

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .github/workflows/update-integration-k8s-kind.yaml
https://github.com/networkservicemesh/cmd-template/issues/20
=> feat: Add job for updating docker images for repository integration-k8s-kind

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .github/workflows/update-cmd-repositories.yaml, .github/workflows/update-integration-k8s-kind.yaml
=> Fix few issues with updating images for repository integration-k8s-kind

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .github/workflows/update-cmd-repositories.yaml, .github/workflows/update-integration-k8s-kind.yaml
1. Respond on comment https://github.com/networkservicemesh/cmd-template/pull/31/files#r517507940
2. Simplify update-cmd-repositories.yaml 
3. Simplify update-integration-k8s-kind.yaml
=> Simplify scripts and review comments

.github/workflows/update-cmd-repositories.yaml
=> Subscribe cmd-nse-icmp-responder on updates from cmd-template

.github/workflows/ci.yaml, .github/workflows/update-integration-k8s-kind.yaml
=> fix: Error "No such file or directory"

.github/workflows/ci.yaml, .github/workflows/update-integration-k8s-kind.yaml
=> fix: cmd-* app should be able to delete a branch in case of its own update

.github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .github/workflows/update-integration-k8s-kind.yaml
=> fix: docker-push job fails and sdk version is not used in case of update from sdk

.github/workflows/docker-push.yaml
=> fix: Replace tag 'master' to 'latest'

.github/workflows/docker-push.yaml
=> fix: split docker image build to separate steps

.github/workflows/ci.yaml
=> fix: docker push job from ci.yaml is not updated

.github/workflows/ci.yaml, .github/workflows/update-integration-k8s-kind.yaml
This PR fixes bugs with creating PRs in next repos
=> Bump short-sha job to v1.2

.github/workflows/ci.yaml, .github/workflows/update-integration-k8s-kind.yaml
=> fix: Add working directory for step "Create branch name"

.github/workflows/update-cmd-repositories.yaml, .github/workflows/update-deployments.yaml
This PR redirects updates from cmd-* apps to https://github.com/networkservicemesh/deployments-k8s
=> feat: Redirect updates to networkservicemesh/deployments-k8s

.github/workflows/update-cmd-repositories.yaml
matrix values can not be compared on job level
=> fix: update-cmd-repositories.yaml  has wrong cond

.github/workflows/update-cmd-repositories.yaml
=> fix: add working-directory

.github/workflows/pr-for-updates.yaml, .github/workflows/update-cmd-repositories.yaml, .syncignore, .templateignore
Currently, updates provided but can not be automatically merged by cmd-*
Example:
https://github.com/networkservicemesh/cmd-nsc/tree/sync/networkservicemesh/cmd-template
This PR fixes the problem.
=> Bump sync-files to v1.0.2

.github/workflows/update-cmd-repositories.yaml
=> Update sync files to v1.0.2 #2

.github/workflows/ci.yaml, .golangci.yml
=> Update golangci linter to v1.34.0

.github/workflows/ci.yaml
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> fix: golangci check fails on the master/main branches

.github/workflows/ci.yaml
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> fix: update-deployments-k8s job should wait for dockerPush

.github/workflows/automerge.yaml, .github/workflows/ci.yaml, .github/workflows/docker-push.yaml, Dockerfile, go.mod, main.go
=> Update cmd-template and fix automerge job

.github/workflows/docker-push.yaml
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> fix: docker push job is not working

.github/workflows/update-deployments.yaml
=> fix: Make consistent sha from 'docker-push-ghcr' and 'update deployments-k8s repository'

.github/workflows/docker-push-ghcr.yml, .github/workflows/update-deployments.yaml
Signed-off-by: Denis Tingaikin <denis.tingajkin@xored.com>
=> Update docker-push-ghcr pattern to fix issues with integration testing

.github/workflows/ci.yaml, .github/workflows/release.yml
https://github.com/networkservicemesh/release/issues/1
=> feat: Add release docker-push-ghcr workflow

.github/workflows/automerge.yaml, .github/workflows/pr-for-updates.yaml, .github/workflows/update-deployments.yaml
Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
part of https://github.com/networkservicemesh/cmd-template/issues/64
=> Updated nsmbot message

.github/workflows/update-deployments.yaml
Signed-off-by: Mikhail Avramenko <avramenkomihail15@gmail.com>
fixes https://github.com/networkservicemesh/deployments-k8s/issues/3375
=> Added missed ci job

.github/workflows/release-deployments.yaml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
https://github.com/networkservicemesh/deployments-k8s/issues/4271
=> Fan-in NSM Releasing

.github/workflows/automerge.yaml, .github/workflows/release-deployments.yaml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
https://github.com/networkservicemesh/deployments-k8s/issues/4271
=> Release-deployments workflow fix

Dockerfile
Issue: https://github.com/networkservicemesh/deployments-k8s/issues/5379
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
=> Update spire version

.github/workflows/update-deployments.yaml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
=> Fix find-and-replace job

.github/workflows/automerge.yaml, .github/workflows/ci.yaml, .github/workflows/docker-push.yaml, .golangci.yml, Dockerfile, go.mod
Closes: https://github.com/networkservicemesh/cmd-template/pull/101
Issue: https://github.com/networkservicemesh/sdk/issues/1264
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>
=> bump: update to go v1.18

.github/workflows/release.yml
Signed-off-by: Nikita Skrynnik <nikita.skrynnik@xored.com>
=> Use proper reusable workflow for docker job

SECURITY.md
Signed-off-by: Szilard Vincze <szilard.vincze@est.tech>
=> Security policy document for NSM repos.

.github/workflows/release.yml
Related to https://github.com/networkservicemesh/integration-k8s-packet/issues/312
=> Fix deprecated Github Action set-output

.golangci.yml, main.go
Fix main package comment
Related to https://github.com/networkservicemesh/sdk/issues/1420
=> Fix linter

.golangci.yml
Related to https://github.com/networkservicemesh/sdk/issues/1420
=> Minimize scope of disabling revive linter

.golangci.yml, Dockerfile, go.mod
https://github.com/networkservicemesh/deployments-k8s/issues/9216
=> Update to go 1.20

.golangci.yml
Use new configuration for `depguard` linter and delete some commented lines
=> [qfix] Update golagnci-lint config file

.github/workflows/docker-push-ghcr.yml, .github/workflows/docker-push.yaml
https://github.com/networkservicemesh/cmd-template/issues/117
=> Use only one trigger for docker-push workflows

.github/workflows/ci.yaml
Issue: https://github.com/networkservicemesh/vpphelper/issues/4
=> Update CI settings

Dockerfile
https://github.com/networkservicemesh/deployments-k8s/issues/10770
=> Update Spire and Delve in Dockerfile

.github/workflows/release.yml
https://github.com/networkservicemesh/.github/issues/67
=> Run release workflow only when CI passes on release branches

.github/workflows/update-deployments.yaml
https://github.com/networkservicemesh/.github/issues/67
=> Remove some triggers in Update deploymets-k8s repository workflow

.github/workflows/release.yml
https://github.com/networkservicemesh/deployments-k8s/issues/11430
=> Delete check-release-branch job from release workflow
